services:
  backend:
    extends:
      file: ./Backend/DocumentManagementSystem/docker-compose.yaml
      service: backend
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - JWT_SECRET=${JWT_SECRET}
    expose:
      - 80
    ports:
      - 1233:80
    networks:
      - default
  frontend:
    extends:
      file: ./Frontend/DocumentManagementSystem/docker-compose.yaml
      service: web
    environment:
      - VITE_BACKEND_URL=http://localhost:1233
      - VITE_FRONTEND_URL=${GOOGLE_REDIRECT_URI}
      - VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - VITE_BASE_URL="/"
    expose:
      - 80
    networks:
      - default
    ports:
      - 5173:80

networks:
  default:
    external:
      name: document-management-system-network
