services:
  backend:
    extends:
      file: ./Backend/DocumentManagementSystem/docker-compose.yaml
      service: backend
      env: 
        - FRONTEND_URL=http://frontend:5173
      expose:
        - 80
      ports:
        - 1234:80
      networks:
        - default
  frontend:
    extends:
      file: ./Frontend/DocumentManagementSystem/docker-compose.yaml
      service: web
      env: 
        - BACKEND_URL=http://backend
      expose:
        - 80
      networks:
        - default
      ports:
        - 5173:80


networks:
  default:
    external:
      name: document-management-system-network
