name: Save Artifacts for Deploy DocumentSystem to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23' 

      - name: Install and Build
        working-directory: Frontend/DocumentManagementSystem
        run: |
          npm install
          npm run build

      - name: Check dist folder contents
        run: ls -al && ls -la Frontend/DocumentManagementSystem/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_branch: gh-pages
          publish_dir: Frontend/DocumentManagementSystem/dist

  deploy:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout main repo with submodules
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Check
        run: ls -al
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
